# version: "3.9"
 
services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: task_prod_api
    container_name: task_prod_api
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    # ports:
    #   - "8000:8000"
    expose:
      - "8000" 
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
    command: /start
    networks:
      - task_prod_nw

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: task_prod_postgres
    container_name: task_prod_postgres
    ports:
      - "5432:5432"
    volumes:
      - post_prod_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - task_prod_nw


  nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: task_nginx
    ports:
      - "8080:80"
    volumes:
      - ./staticfiles:/app/staticfiles
      - logs_store:/var/log/nginx
    depends_on:
      - api
    networks:
      - task_prod_nw

networks:
  task_prod_nw:
    external: true

volumes:
  post_prod_postgres_data: {}
  logs_store: {}




